# .github/environments/production.yml
name: production
protection_rules:
  - type: required_reviewers
    required_reviewers: 2
  - type: wait_timer
    wait_timer: 5
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: falses