# .github/environments/staging.yml
name: staging
protection_rules:
  - type: required_reviewers
    required_reviewers: 1
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  custom_branches:
    - main
    - develop